
package action.client.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddNumbersServiceName", targetNamespace = "http://addnumbers.org/targetNamespace", wsdlLocation = "http://localhost:8080/addressing?wsdl")
public class AddNumbersServiceName
    extends Service
{

    private final static URL ADDNUMBERSSERVICENAME_WSDL_LOCATION;
    private final static WebServiceException ADDNUMBERSSERVICENAME_EXCEPTION;
    private final static QName ADDNUMBERSSERVICENAME_QNAME = new QName("http://addnumbers.org/targetNamespace", "AddNumbersServiceName");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/addressing?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDNUMBERSSERVICENAME_WSDL_LOCATION = url;
        ADDNUMBERSSERVICENAME_EXCEPTION = e;
    }

    public AddNumbersServiceName() {
        super(__getWsdlLocation(), ADDNUMBERSSERVICENAME_QNAME);
    }

    public AddNumbersServiceName(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDNUMBERSSERVICENAME_QNAME, features);
    }

    public AddNumbersServiceName(URL wsdlLocation) {
        super(wsdlLocation, ADDNUMBERSSERVICENAME_QNAME);
    }

    public AddNumbersServiceName(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDNUMBERSSERVICENAME_QNAME, features);
    }

    public AddNumbersServiceName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddNumbersServiceName(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddNumbersName
     */
    @WebEndpoint(name = "AddNumbersPortName")
    public AddNumbersName getAddNumbersPortName() {
        return super.getPort(new QName("http://addnumbers.org/targetNamespace", "AddNumbersPortName"), AddNumbersName.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddNumbersName
     */
    @WebEndpoint(name = "AddNumbersPortName")
    public AddNumbersName getAddNumbersPortName(WebServiceFeature... features) {
        return super.getPort(new QName("http://addnumbers.org/targetNamespace", "AddNumbersPortName"), AddNumbersName.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDNUMBERSSERVICENAME_EXCEPTION!= null) {
            throw ADDNUMBERSSERVICENAME_EXCEPTION;
        }
        return ADDNUMBERSSERVICENAME_WSDL_LOCATION;
    }

}
